### ISSUE TITLE
More lines in frame

### ISSUE THREAD

**Issue by ai** [hhsnopek/code-frame#13]
Babel shows 2 lines before issue and 2 after. But `code-frame` only 1 line before and 1 after.

Should we make frame bigger? I think 3 lines is too short. Also again, UI consistency is awesome :D.

**Comment by ai** [comment]
Here is my current code, you can take some ideas to `code-frame`:

``` js
let lines = css.split(/\r?\n/);
let start = Math.max(this.line - 3, 0);
let end   = Math.min(this.line + 3, lines.length);

let maxWidth = String(end).length;

return lines.slice(start, end).map( (line, index) => {
    let number = start + 1 + index;
    let padded = (' ' + number).slice(-maxWidth);
    let gutter = ' ' + padded + ' | ';
    if ( number === this.line ) {
        let spaces = pad(maxWidth) + '   | ' + pad(this.column - 1);
        return '>' + gutter + line + '\n' + spaces + '^';
    } else {
        return ' ' + gutter + line;
    }
}).join('\n');
```

**Comment by hhsnopek** [comment]
So this is one of the things I didn't like from babel-code-frame. While it's nice to see more context around the offending line, it's possible to over clutter the code-frame. The context of the error should only be the offending line so that you can clearly see what's going on. I even think the line below it is a stretch, but I can see how it could be useful for errors that are due to a new line. As reluctant as I am about this, I'm open to updating the below the offending line to display the line that is - though I'd like you to take a look below to see what I mean. I'd personally prefer to remove the line after the offending line as shown in my first example to increase the readability. I know UI constancy is great, but I don't agree in the way babel-code-frame handled their frame

#### Best case for developers to provide clear context to the offending line

```
  3 |    for ( ; i < len; ++i ) {
> 4 |        total += arguments[z];
    |                           ^
```

#### (Current implementation) Minimal and easy to read, even if it  does remove the line below it

```
  3 |    for ( ; i < len; ++i ) {
> 4 |        total += arguments[z];
    |                           ^
  5 |
```

#### Adding the line below takes away a little of the readability

```
  3 |    for ( ; i < len; ++i ) {
> 4 |        total += arguments[z];
    |                           ^
  5 |        console.log(total);
```

#### Way too much context

```
  2 |    var total = 0, i = 0, len = arguments.length;
  3 |    for ( ; i < len; ++i ) {
> 4 |        total += arguments[z];
    |                           ^
  5 |        console.log(total);
  6 |    }
```

**Comment by hhsnopek** [comment]
We could add this feature thru #6, thus having the best of both worlds. I personally think that this shouldn't be optional as I'd like to keep this as minimal as possible, but we can make this an optional adjustment that defaults to 2 lines of source as shown in the first example.

Here's an example interface: `frame(code, line[, col, linesOfCode])`

**Comment by hhsnopek** [comment]
whatcha thinking @ai?

**Comment by ai** [comment]
`frame(code, line[, col, linesOfCode])` is OK

**Comment by hhsnopek** [comment]
I'll publish this tonight

## 

Henry Snopek

**Comment by hhsnopek** [comment]
Hey @ai - just need to fix some tests, weird `\t` bug that I need to solve and add new tests! I'll dive in again tomorrow evening - thanks for the patience
